add need workflow_run

diff --git a/.github/workflows/tf-apply-ci.yml b/.github/workflows/tf-apply-ci.yml
--- a/.github/workflows/tf-apply-ci.yml
+++ b/.github/workflows/tf-apply-ci.yml
@@ -1,6 +1,6 @@
-name: 1 - [PLAN] Terraform Plan
+name: 2 - [APPLY] Terraform Apply
 
-on: push
+on: workflow_dispatch
 
 env:
   AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
@@ -13,29 +13,27 @@ env:
   TF_VAR_azure_key_pub: ${{secrets.TF_VAR_azure_key_pub}}
 
 jobs:
-  terraform_plan:
-    name: Terraform Plan
+  terraform_apply:
+    name: Terraform Apply
     runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
     steps:
+    - name: Check Test Status
+      run: |
+        if [ "${{ needs.terraform_test.outputs.tests-passed }}" != "true" ]; then
+          echo "Tests failed, skipping Terraform Apply."
+          exit 1
+        fi
+        
     - uses: actions/checkout@v4
     - uses: hashicorp/setup-terraform@v3
-    
-    - name: Terraform fmt
-      id: fmt
-      run: terraform fmt -check
-      continue-on-error: true
-    
+
     - name: Terraform Init
       id: init
       run: terraform init
-    
-    - name: Terraform Validate
-      id: validate
-      run: terraform validate -no-color
-    
-    - name: Terraform Plan
-      id: plan
-      run: terraform plan
+
+    - name: Terraform Apply
+      id: apply
+      run: terraform apply -auto-approve
